---
title: Plagiobothrys tenellus
description: ''
date: 2025-06-04
weight: 10
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r, echo=FALSE, include=FALSE}
source("R/site_globals.R")
source("scripts/geomUtils.R")
source("scripts/config.R")
library(leaflet)
library(rmarkdown)
library(dplyr)
library(ggplot2)
```

This map shows the accumulated search effort for Plagiobothrys tenellus over historical community PT1

```{r}
target_agm <- read.csv("Analysis_outputs/Intermediate/Plagiobothrys tenellus_accepted_grouped_merged.csv")
target_historical <- target_agm %>% dplyr::filter(assigned_community == "PT1")
target_sf = assign_cell_geometry_sf(target_historical, galgrid)

pal <- colorNumeric(palette = "viridis", domain = range(c(0, target_sf$search_effort), na.rm = TRUE))
m <- leaflet(data = target_sf) %>%
  # Add a Tiles layer to the map
  addProviderTiles("Esri.WorldImagery") %>%
  # Add the grid layer to the map
  addPolygons(fillColor = ~pal(search_effort), fillOpacity = 0.8, 
              color = "#BDBDC3", weight = 1) %>%
  # Add a legend
  addLegend(pal = pal, values = c(0, max(target_sf$search_effort, na.rm = TRUE)),
            opacity = 0.8, title = "Accumulated Search Effort in ks")

# Print the map
m

```
```{r}
target_stats <- read.csv("Analysis_outputs/Intermediate/Plagiobothrys tenellus_stats.csv")
target_stats_historical <- target_stats %>% dplyr::filter(Population == "PT1")
paged_table(target_stats_historical)
```

This map shows the accumulated search effort for Plagiobothrys tenellus over historical community PT2

```{r}

target_historical <- target_agm %>% dplyr::filter(assigned_community == "PT2")
target_sf = assign_cell_geometry_sf(target_historical, galgrid)

pal <- colorNumeric(palette = "viridis", domain = range(c(0, target_sf$search_effort), na.rm = TRUE))
m <- leaflet(data = target_sf) %>%
  # Add a Tiles layer to the map
  addProviderTiles("Esri.WorldImagery") %>%
  # Add the grid layer to the map
  addPolygons(fillColor = ~pal(search_effort), fillOpacity = 0.8, 
              color = "#BDBDC3", weight = 1) %>%
  # Add a legend
  addLegend(pal = pal, values = c(0, max(target_sf$search_effort, na.rm = TRUE)),
            opacity = 0.8, title = "Accumulated Search Effort in ks")

# Print the map
m

```
```{r}
target_stats <- read.csv("Analysis_outputs/Intermediate/Plagiobothrys tenellus_stats.csv")
target_stats_historical <- target_stats %>% dplyr::filter(Population == "PT2")
paged_table(target_stats_historical)
```
