---
title: Example
description: ''
date: 2025-06-04
weight: 5
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r, echo=FALSE, include=FALSE}
source("scripts/geomUtils.R")
source("scripts/config.R")
library(leaflet)
```

This map shows the accumulated search effort for Primula pauciflora over its historical habitat covering 9 grid cells
in Bellhouse Park:

```{r}
prim_agm <- read.csv("Analysis_outputs/Intermediate/Primula pauciflora_accepted_grouped_merged.csv")
prim_historical <- prim_agm %>% dplyr::filter(assigned_community == 77)
prim_sf = assign_cell_geometry_sf(prim_historical, galgrid)

pal <- colorNumeric(palette = "viridis", domain = range(c(0, prim_sf$search_effort), na.rm = TRUE))
m <- leaflet(data = prim_sf) %>%
  # Add a Tiles layer to the map
  addTiles() %>%
  # Add the grid layer to the map
  addPolygons(fillColor = ~pal(search_effort), fillOpacity = 0.8, 
              color = "#BDBDC3", weight = 1) %>%
  # Add a legend
  addLegend(pal = pal, values = c(0, max(prim_sf$search_effort, na.rm = TRUE)),
            opacity = 0.8, title = "Accumulated Search Effort in ks")

# Print the map
m

```